const quote='https://wa.me/5531993416774?text='+encodeURIComponent('Olá, Luiz! Vi seu portfólio e gostaria de solicitar um orçamento para um projeto 3D.');
document.querySelectorAll('[data-quote]').forEach(a=>{a.href=quote;a.target='_blank';a.rel='noopener noreferrer'});
const models=[['philipe','Philipe','renders/philipe.png'],['joao','João'],['milena','Milena','renders/milena (2).png'],['vanellope','Vanellope'],['ania','Ania'],['miner','Mineirinho / Miner','renders/miner1.png'],['roger','Roger']];
const modelVersions={ania:'20260922-161330',philipe:'20260922-160317',milena:'20260922-161206'};
let paused=matchMedia('(prefers-reduced-motion: reduce)').matches;
const motion=document.querySelector('#motion');
function updateMotion(){motion.textContent=paused?'Ativar rotação':'Pausar rotação';motion.setAttribute('aria-pressed',String(paused))}updateMotion();motion.onclick=()=>{paused=!paused;updateMotion()};
let engine;function getEngine(){return engine??=Promise.all([import('three'),import('three/addons/loaders/GLTFLoader.js'),import('three/addons/loaders/HDRLoader.js')]).catch(e=>{engine=null;throw e})}
// One HDR download shared across viewers; each renderer prepares its own environment map.
let studioHDR;
function getStudioHDR(THREE,HDRLoader){return studioHDR??=new HDRLoader().loadAsync('environments/studio_small_03_1k.hdr').then(texture=>{texture.mapping=THREE.EquirectangularReflectionMapping;return texture}).catch(error=>{studioHDR=null;throw error})}
const entries=models.map(([id,name,poster],i)=>{const card=document.createElement('article');card.className='character';card.id='character-'+id;card.innerHTML='<div class="stage"><span class="number">'+String(i+1).padStart(2,'0')+' / CHARACTER</span>'+(poster?'<img class="poster" loading="lazy" src="'+poster+'" alt="Render de '+name+'">':'<div class="placeholder" aria-hidden="true">'+name[0]+'</div>')+'<button class="load" aria-label="Carregar '+name+' em 3D">'+(id==='milena'?'Explorar em 3D · 59 MB':'Explorar em 3D')+'</button><span class="model-status" role="status">'+(id==='milena'?'Carrega somente quando você escolher':'Prévia 3D ao entrar na tela')+'</span></div><div class="character-info"><div><h3>'+name+'</h3><p>Stylized character / 3D model</p></div><span>3D ↗</span></div>';document.querySelector('#characters').append(card);const e={id,name,card,stage:card.querySelector('.stage'),button:card.querySelector('button'),status:card.querySelector('.model-status'),visible:false,loading:false,loaded:false,failed:false};e.button.onclick=()=>load(e);return e});
let queue=Promise.resolve();
const observer=new IntersectionObserver(changes=>{for(const change of changes){const e=entries.find(e=>e.stage===change.target);e.visible=change.isIntersecting;if(e.visible&&!e.loaded&&!e.loading&&!e.failed&&e.id!=='milena'&&!navigator.connection?.saveData){e.loading=true;queue=queue.then(()=>{if(!e.visible){e.loading=false;return}return load(e)}).catch(()=>{})}}},{threshold:0.08});entries.forEach(e=>observer.observe(e.stage));
async function load(e){if(e.loaded||e.busy)return;e.busy=true;e.loading=true;e.button.hidden=true;e.status.textContent='Carregando '+e.name+'…';let renderer;try{const [THREE,{GLTFLoader},{HDRLoader}]=await getEngine();renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.0;const scene=new THREE.Scene();const fill=new THREE.HemisphereLight(0xffffff,0x888888,0.35);scene.add(fill);const key=new THREE.DirectionalLight(0xffffff,0.8);key.position.set(3,5,4);scene.add(key);const rim=new THREE.DirectionalLight(0xe6f2ff,0.35);rim.position.set(-3,3,-3);scene.add(rim);
try{scene.environment=await getStudioHDR(THREE,HDRLoader);scene.environmentIntensity=0.85;scene.environmentRotation.y=Math.PI/4;}catch(error){console.warn('HDR indisponível; usando iluminação de reserva.',error);fill.intensity=1.2;key.intensity=2;}
const gltf=await new GLTFLoader().loadAsync('modelos/'+e.id+'.glb'+(modelVersions[e.id]?'?v='+modelVersions[e.id]:''),p=>{if(p.total)e.status.textContent='Carregando '+Math.round(p.loaded/p.total*100)+'%'});const model=gltf.scene;model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model);const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());const scale=2.7/Math.max(size.y,size.x,size.z);const pivot=new THREE.Group();model.position.sub(center);const wrapper=new THREE.Group();wrapper.add(model);wrapper.scale.setScalar(scale);pivot.add(wrapper);scene.add(pivot);const camera=new THREE.PerspectiveCamera(32,1,.01,100);function resize(){const w=e.stage.clientWidth,h=e.stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;const radius=Math.max(size.x,size.y,size.z)*scale/2;camera.position.set(0,.08,radius/Math.sin(THREE.MathUtils.degToRad(16))/Math.min(1,camera.aspect)*1.12);camera.lookAt(0,0,0);camera.updateProjectionMatrix();renderer.render(scene,camera)}e.stage.append(renderer.domElement);renderer.domElement.tabIndex=0;renderer.domElement.setAttribute('role','img');renderer.domElement.setAttribute('aria-label',e.name+' em 3D. Arraste ou use as setas para girar.');let dragging=false,lastX=0;renderer.domElement.addEventListener('pointerdown',ev=>{dragging=true;lastX=ev.clientX;renderer.domElement.setPointerCapture(ev.pointerId)});renderer.domElement.addEventListener('pointermove',ev=>{if(dragging){pivot.rotation.y+=(ev.clientX-lastX)*.012;lastX=ev.clientX;renderer.render(scene,camera)}});for(const event of ['pointerup','pointercancel','lostpointercapture'])renderer.domElement.addEventListener(event,()=>dragging=false);renderer.domElement.addEventListener('keydown',ev=>{if(['ArrowLeft','ArrowRight'].includes(ev.key)){ev.preventDefault();pivot.rotation.y+=ev.key==='ArrowLeft'?-.15:.15;renderer.render(scene,camera)}});new ResizeObserver(resize).observe(e.stage);resize();e.render=(delta)=>{if(!paused&&!dragging)pivot.rotation.y+=delta*.15;renderer.render(scene,camera)};e.loaded=true;e.stage.querySelector('.poster, .placeholder')?.remove();e.status.textContent='Arraste para girar · ← →';}catch(error){console.error('Falha ao carregar '+e.id,error);renderer?.dispose();renderer?.domElement.remove();e.failed=true;e.button.hidden=false;e.button.textContent='Tentar novamente';e.status.textContent='Não foi possível abrir o 3D. Tente novamente.'}finally{e.loading=false;e.busy=false}}
let last=0;function frame(now){const delta=Math.min((now-last)/1000,.05);if(now-last>=33){last=now;if(!document.hidden)entries.forEach(e=>{if(e.visible&&e.loaded)e.render(delta)})}requestAnimationFrame(frame)}requestAnimationFrame(frame);



